# Generates graphviz file from the compose.awk output
# loriacarlos@gmail.com
# compose_output/composed_plan.txt --> gv_output/study_plan.gv
# To run
# awk -f gengraph.awk compose_output/composed_plan.txt > gv_output/study_plan.gv
BEGIN{
    FS="::";
	printf "digraph prueba {\n";
    printf "ranksep=0.50;\n";
     printf "Admission[shape=circle, color=gray, fontcolor=black, style=filled ];\n";
	printf "node [shape=circle, color=red, fontcolor = " "blue , fixedsize =false""]\n";
	printf "edge[color=gray]\n";
}
# Expected input record format generated by compose
# nn::code::description::[2345](::req)*::(bsc|dipl)::(level|_)::(cycle|_)

($1>40){
tam=NF;
tamN=tam-3;
 if(tam>8){
 num=5;
   do {
          printf  $num "->" $2";\n";
        num++
    } while (num <= tamN)
 }else{printf  $5 "-> " $2 ";\n";}
}

END{
  
	printf "}\n";
}
