# Generates prolog file from compose.awk output
# loriacarlos@gmail.com
# compose_output/composed_plan.txt --> prolog_output/study_plan.pl
# To run
# awk -f src/prolog.awk output/composed_plan.txt > prolog_output/study_plan.pl
BEGIN {
	FS = "::";
	printf "%%%%% Study Plan %%%%%\n";
	printf ":- discontiguous course/1.\n";
	printf ":- discontiguous course/8.\n";
	printf ":- discontiguous course_req/2.\n";
}
# Expected input record format generated by compose
# nn::code::description::credits[2345](::req)*::(bsc|dipl)::(level|_)::(cycle|_)
# req ~ EI(F|G)...O? | LIX...
{
	printf "% --- '"; 
	printf "%s' ---\n", $2;
	printf "course('%s').\n", $2;
	#      codigo, numero de linea, regular/opcional, plan, creditos, año, ciclo, descripcion
	printf "course('%s', %s, %s, regular, %s, '%s').\n", $2, $1, $6, $4, $3;
	printf "course_req('%s', '%s').\n", $2, $5;
}
END{
}